kb(grid,tooltip):tooltip in grid example changes
telerik/blazor-ui pull request #141
Opened 2021-12-12 22:29 UTC by xristianstefanov

- Added a new page with an example that shows only one instance of the Tooltip for the whole Grid.

Related to: https://github.com/telerik/blazor/issues/2917

2021-12-14 06:00 UTC, marin-bratanov commented
why was "groupable" removed? Does this work as-is without any calls for the tooltip to re-evaluate its target? Is it "automatic" or through explicit API? There should also be an update on the readme to explain the two pages and how each works.

2021-12-23 14:22 UTC, xristianstefanov commented
> why was "groupable" removed? Does this work as-is without any calls for the tooltip to re-evaluate its target? Is it "automatic" or through explicit API? There should also be an update on the readme to explain the two pages and how each works.

Hi Marin! The "groupable" was unintentionally removed. The tooltip re-evaluates its targets "automatically". I also fixed the readme.

2021-12-23 14:28 UTC, dimodi commented on tooltip/in-grid/Pages/Index.razor
> +                    <span data-employeeId="@employee.Id" id="@( "tooltip-target")">@employee.Name</span>
```suggestion
                    <span data-employeeId="@employee.Id" id="tooltip-target">@employee.Name</span>
```

2021-12-23 14:29 UTC, dimodi commented on tooltip/in-grid/Pages/Index.razor
> +<TelerikTooltip TargetSelector="#tooltip-target"
```suggestion
<TelerikTooltip TargetSelector=".tooltip-target"
```

2021-12-23 14:30 UTC, dimodi requested changes
The single Tooltip example cannot rely on an ID selector.

2021-12-23 14:42 UTC, dimodi approved these changes

2021-12-23 14:47 UTC, merged